//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Inventories = new HashSet<Inventory>();
        }

        public User(string username, string email, string password)
        {
            Username = username;
            Email = email;
            Password = password;
            DietId = 1;
            GuiltLevel = 1;
        }

        public int UserId { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int GuiltLevel { get; set; }
        public int DietId { get; set; }
    
        public virtual Diet Diet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory> Inventories { get; set; }

        public override string ToString()
        {
            return $"{{{nameof(UserId)}={UserId.ToString()}, {nameof(Username)}={Username}, {nameof(Email)}={Email}, {nameof(Password)}={Password}, {nameof(GuiltLevel)}={GuiltLevel.ToString()}, {nameof(DietId)}={DietId.ToString()}, {nameof(Diet)}={Diet}, {nameof(Inventories)}={Inventories}}}";
        }
    }
}
