// <auto-generated />
namespace Capstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class guid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(guid));
        
        string IMigrationMetadata.Id
        {
            get { return "202011181728288_guid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
